# Generated by Django 3.1 on 2020-08-27 04:09

import back.models.worker_document
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0020_auto_20200827_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=back.models.worker_document.project_docs_path),
        ),
    ]
