# Generated by Django 3.1 on 2020-08-05 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SafeMan', 'Safety Manager'), ('SecMan', 'Security Manager'), ('SecOff', 'Safety Officer'), ('SiteOwn', 'Site Oswner'), ('WorkOwn', 'Owner of Work'), ('SecGrd', 'Security Guards')], default='SiteOwn', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Default', 'Contractor')], default='Default', max_length=10)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='back.company')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentWorkerAssign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('birthday', models.DateField()),
                ('company', models.CharField(max_length=64)),
                ('card_number_id', models.CharField(max_length=64)),
                ('license_number', models.CharField(max_length=64)),
                ('passport', models.CharField(max_length=64, null=True)),
                ('safety_green_card', models.CharField(max_length=64)),
                ('position_in_company', models.CharField(max_length=64)),
                ('workers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.contractor')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('text', 'Text'), ('password', 'Password'), ('email', 'Email'), ('checkbox', 'Checkbox'), ('select', 'Select')], default='text', max_length=10)),
                ('type_values', models.TextField()),
                ('placeholder', models.CharField(max_length=64)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.template')),
            ],
        ),
        migrations.AddField(
            model_name='template',
            name='templates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.work'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.work')),
            ],
        ),
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.project')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.worker')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.TextField(null=True)),
                ('str_value', models.CharField(max_length=64, null=True)),
                ('doc_items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.templateitem')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.document')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentAssign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('change_date', models.DateField(auto_now=True)),
                ('approve', models.BooleanField(null=True)),
                ('last_approve_date', models.DateField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.document')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.clientmanager')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='managers',
            field=models.ManyToManyField(through='back.DocumentAssign', to='back.ClientManager'),
        ),
        migrations.AddField(
            model_name='document',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.template'),
        ),
        migrations.AddField(
            model_name='document',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.worker'),
        ),
        migrations.AddField(
            model_name='clientmanager',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='back.company'),
        ),
        migrations.AddField(
            model_name='clientmanager',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClientAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Administrator')], default='Admin', max_length=10)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='back.company')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
