# Generated by Django 3.1 on 2020-08-10 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientadmin',
            options={'verbose_name': 'Client Administrator'},
        ),
    ]
