# Generated by Django 3.1 on 2020-08-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_auto_20200810_0648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientmanager',
            old_name='role',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='clientadmin',
            name='role',
        ),
        migrations.AddField(
            model_name='foxuser',
            name='role',
            field=models.CharField(choices=[('CliMan', 'Client Manager'), ('CliAdm', 'Client Admin'), ('Contr', 'Contractor'), ('Dum', 'Dummy')], default='Dum', max_length=16),
        ),
    ]
