# Generated by Django 3.1 on 2020-08-13 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_auto_20200812_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientmanager',
            options={'verbose_name': 'Client Manager'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='contractor',
            options={'verbose_name': 'Contractor'},
        ),
        migrations.RenameField(
            model_name='contractor',
            old_name='type',
            new_name='contractor_type',
        ),
    ]
