# Generated by Django 3.1 on 2020-08-13 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_auto_20200813_0803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='workers',
            new_name='contractor',
        ),
    ]
