# Generated by Django 3.1 on 2020-08-13 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_auto_20200813_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='template',
            name='templates',
        ),
        migrations.AddField(
            model_name='project',
            name='contractor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='back.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='Project',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='back.project'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Work',
        ),
    ]
