# Generated by Django 3.1 on 2020-08-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_auto_20200814_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contractors',
            field=models.ManyToManyField(related_name='projects', to='back.Contractor'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
