# Generated by Django 3.1 on 2020-08-17 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_auto_20200816_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templateitem',
            old_name='type',
            new_name='type_choice',
        ),
        migrations.RemoveField(
            model_name='project',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='template',
            name='Project',
        ),
        migrations.RemoveField(
            model_name='templateitem',
            name='items',
        ),
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='back.company'),
        ),
        migrations.AddField(
            model_name='template',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='back.project'),
        ),
        migrations.AddField(
            model_name='templateitem',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='back.template'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='back.contractor'),
        ),
    ]
