# Generated by Django 3.1 on 2020-08-13 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_auto_20200813_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='contractor',
            new_name='Company',
        ),
    ]
