# Generated by Django 3.1 on 2020-08-13 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0007_auto_20200813_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Worker'},
        ),
        migrations.RenameField(
            model_name='permit',
            old_name='project',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='permit',
            old_name='worker',
            new_name='Worker',
        ),
    ]
