# Generated by Django 3.1 on 2020-08-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0007_auto_20200817_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='templates',
            field=models.ManyToManyField(related_name='projects', to='back.Template'),
        ),
    ]
