# Generated by Django 3.1 on 2020-08-20 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0008_auto_20200817_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contractors',
        ),
        migrations.AddField(
            model_name='project',
            name='contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='back.contractor'),
        ),
    ]
