# Generated by Django 3.1 on 2020-08-13 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0009_auto_20200813_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentassign',
            options={'verbose_name_plural': 'Document Assignments'},
        ),
    ]
