# Generated by Django 3.1 on 2020-08-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0010_remove_project_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
