# Generated by Django 3.1 on 2020-08-22 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0011_auto_20200822_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='company',
        ),
    ]
