# Generated by Django 3.1 on 2020-08-23 18:31

import back.models.document
import back.models.worker_document
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("back", "0012_remove_worker_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=back.models.worker_document.project_docs_path,
                    ),
                ),
                ("origin_filename", models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(model_name="templateitem", name="template",),
        migrations.RemoveField(model_name="document", name="Worker",),
        migrations.RemoveField(model_name="document", name="managers",),
        migrations.RemoveField(model_name="document", name="template",),
        migrations.AddField(
            model_name="document",
            name="documents",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="back.project",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="file",
            field=models.FilePathField(
                null=True, path=back.models.document.project_docs_path
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="name",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="origin_filename",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="target_type",
            field=models.CharField(
                choices=[("Contr", "Contractor"), ("Work", "Worker")],
                default="Contr",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="document", name="url_to_doc", field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("Created", "Created"),
                    ("Submitted", "Submitted"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Works_started", "Works started"),
                    ("Works_finished", "Works finished"),
                    ("Extended", "Extended"),
                    ("Closed", "Closed"),
                ],
                default="Created",
                max_length=16,
            ),
        ),
        migrations.DeleteModel(name="DocumentItem",),
        migrations.DeleteModel(name="Template",),
        migrations.DeleteModel(name="TemplateItem",),
        migrations.AddField(
            model_name="workerdocument",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="worker_documents",
                to="back.document",
            ),
        ),
        migrations.AddField(
            model_name="workerdocument",
            name="worker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="related_documents",
                to="back.document",
            ),
        ),
    ]
