# Generated by Django 3.1 on 2020-08-24 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0013_auto_20200823_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='documents',
        ),
        migrations.AddField(
            model_name='document',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='back.project'),
        ),
    ]
