# Generated by Django 3.1 on 2020-08-25 11:18

import back.models.document
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0015_auto_20200825_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(null=True, upload_to=back.models.document.project_docs_path),
        ),
    ]
