# Generated by Django 3.1 on 2020-08-25 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0016_auto_20200825_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='origin_filename',
        ),
    ]
