# Generated by Django 3.1 on 2020-08-26 13:30

import back.models.document
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0017_remove_document_origin_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='workers',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='back.Worker'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=back.models.document.project_docs_path),
        ),
        migrations.AlterField(
            model_name='document',
            name='url_to_doc',
            field=models.URLField(blank=True, null=True),
        ),
    ]
