# Generated by Django 3.1 on 2020-08-27 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("back", "0019_auto_20200826_1630"),
    ]

    operations = [
        migrations.RemoveField(model_name="workerdocument", name="origin_filename",),
        migrations.AddField(
            model_name="project",
            name="responsible_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects_to_manage",
                to="back.worker",
            ),
        ),
    ]
