# Generated by Django 3.1 on 2020-08-31 05:27

import back.models.worker
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0021_auto_20200831_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='chemical_handling_permit',
            field=models.FileField(blank=True, null=True, upload_to=back.models.worker.project_docs_path),
        ),
        migrations.AddField(
            model_name='worker',
            name='cold_work_permit',
            field=models.FileField(blank=True, null=True, upload_to=back.models.worker.project_docs_path),
        ),
        migrations.AddField(
            model_name='worker',
            name='confined_space_permit',
            field=models.FileField(blank=True, null=True, upload_to=back.models.worker.project_docs_path),
        ),
        migrations.AddField(
            model_name='worker',
            name='hot_work_permit',
            field=models.FileField(blank=True, null=True, upload_to=back.models.worker.project_docs_path),
        ),
        migrations.AddField(
            model_name='worker',
            name='lifting_work_permit',
            field=models.FileField(blank=True, null=True, upload_to=back.models.worker.project_docs_path),
        ),
        migrations.AddField(
            model_name='worker',
            name='work_alone_permit',
            field=models.FileField(blank=True, null=True, upload_to=back.models.worker.project_docs_path),
        ),
        migrations.AddField(
            model_name='worker',
            name='work_at_height_permit',
            field=models.FileField(blank=True, null=True, upload_to=back.models.worker.project_docs_path),
        ),
        migrations.AddField(
            model_name='worker',
            name='work_at_sensitive_area_permit',
            field=models.FileField(blank=True, null=True, upload_to=back.models.worker.project_docs_path),
        ),
        migrations.AddField(
            model_name='worker',
            name='workers',
            field=models.FileField(blank=True, null=True, upload_to=back.models.worker.project_docs_path),
        ),
    ]
