# Generated by Django 3.1 on 2020-08-31 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0022_auto_20200831_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='workers',
        ),
    ]
