# Generated by Django 3.1 on 2020-08-31 06:17

import back.models.worker
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0023_remove_worker_workers'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='safety_quiz_answer',
            field=models.FileField(blank=True, null=True, upload_to=back.models.worker.project_docs_path),
        ),
    ]
