# Generated by Django 3.1 on 2020-08-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0025_auto_20200831_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='related_company',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
