# Generated by Django 3.1 on 2020-09-01 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0027_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foxuser',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fox_users', to='back.company'),
        ),
    ]
