# Generated by Django 3.1 on 2020-09-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0028_auto_20200901_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
