# Generated by Django 3.1 on 2020-09-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0030_auto_20200901_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmanager',
            name='department',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='clientmanager',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
