# Generated by Django 3.1 on 2020-09-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0031_auto_20200901_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Deprecated', 'Deprecated')], default='Pending', max_length=16),
        ),
    ]
