# Generated by Django 3.1 on 2020-09-04 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0032_auto_20200902_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='target_type',
        ),
    ]
