# Generated by Django 3.1 on 2020-09-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0034_permit_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='trade_competency',
            field=models.CharField(choices=[('Civ', 'Civil'), ('Electr', 'Electrical'), ('Mech', 'Mechanical'), ('Infra', 'Infra'), ('Gen', 'General'), ('Safe', 'Safety'), ('Secur', 'Security')], default='Gen', max_length=16),
        ),
        migrations.AlterField(
            model_name='worker',
            name='position_in_company',
            field=models.CharField(choices=[('Weld', 'Welder'), ('Fit', 'Fitter'), ('Help', 'Helper'), ('Rig', 'Rigger'), ('SafeOff', 'Safety Officer'), ('Plumb', 'Plumber'), ('Tech', 'Technician'), ('Electr', 'Electrician'), ('FlrInst', 'Flooring Installer'), ('HVACInst', 'HVAC Installer'), ('InsInst', 'Insulation Installer'), ('Surv', 'Surveyor'), ('BrcMans', 'Brick Manson'), ('Roof', 'Roofer'), ('SiteSuper', 'Site Supervisor'), ('Other', 'Other')], default='Other', max_length=16),
        ),
    ]
