# Generated by Django 3.1 on 2020-09-10 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0035_auto_20200910_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
