# Generated by Django 3.1 on 2020-09-11 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0036_worker_deleted'),
        ('back', '0022_auto_20200902_0645'),
    ]

    operations = [
    ]
