# Generated by Django 3.1 on 2020-09-13 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0038_workerspecialcompetency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='competency_issued_by',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='special_competency',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='special_competency_scan',
        ),
    ]
