# Generated by Django 3.1 on 2020-09-14 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0039_auto_20200913_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerspecialcompetency',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_competencies', to='back.worker'),
        ),
    ]
