# Generated by Django 3.1 on 2020-09-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0040_auto_20200914_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerspecialcompetency',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
