# Generated by Django 3.1 on 2020-09-21 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0042_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='manager',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='back.clientmanager'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='back.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
