# Generated by Django 3.1 on 2020-09-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0044_project_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientmanager',
            name='name',
        ),
        migrations.AddField(
            model_name='foxuser',
            name='name',
            field=models.CharField(default='BarFoo', max_length=128),
        ),
    ]
