# Generated by Django 3.1 on 2020-09-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0046_contractor_company_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='phone_number',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
