# Generated by Django 3.1 on 2020-09-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0048_auto_20200923_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_time',
        ),
        migrations.AddField(
            model_name='project',
            name='extend_date',
            field=models.DateTimeField(null=True),
        ),
    ]
