# Generated by Django 3.1 on 2020-09-28 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0050_auto_20200928_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='emitted',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2020, 9, 28, 12, 15, 42, 944258)),
            preserve_default=False,
        ),
    ]
