# Generated by Django 3.1 on 2020-09-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0051_notification_emitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='emitted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
