# Generated by Django 3.1 on 2020-10-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0052_auto_20200928_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='forward_link',
            field=models.URLField(default='https://www.google.com/'),
        ),
    ]
