# Generated by Django 3.1 on 2020-10-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0054_auto_20201001_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foxuser',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
