# Generated by Django 3.1 on 2020-10-07 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0055_auto_20201004_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permit',
            name='Project',
        ),
        migrations.RemoveField(
            model_name='permit',
            name='Worker',
        ),
        migrations.AddField(
            model_name='permit',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='permits', to='back.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permit',
            name='worker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='permits', to='back.worker'),
            preserve_default=False,
        ),
    ]
