# Generated by Django 3.1 on 2020-10-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0056_auto_20201007_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
