# Generated by Django 3.1 on 2020-10-09 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0057_auto_20201007_0539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permit',
            name='end_date',
        ),
    ]
