# Generated by Django 3.1 on 2020-10-16 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0058_remove_permit_end_date'),
        ('back', '0058_auto_20201009_0855'),
    ]

    operations = [
    ]
