# Generated by Django 3.1 on 2020-10-19 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0059_merge_20201016_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='registration_number',
        ),
    ]
