# Generated by Django 3.1 on 2020-10-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0061_worker_card_number_id_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='card_number_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
