# Generated by Django 3.1 on 2020-10-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0061_worker_card_number_id_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='related_company',
            field=models.CharField(max_length=128, null=True, verbose_name='Company/Organization'),
        ),
    ]
