# Generated by Django 3.1 on 2020-10-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0062_auto_20201022_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='card_number_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='passport',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
