# Generated by Django 3.1 on 2020-10-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0062_auto_20201022_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='related_company',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
