# Generated by Django 3.1 on 2020-10-22 06:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0064_auto_20201022_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='emitted',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
