# Generated by Django 3.1 on 2020-10-23 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0063_auto_20201022_1457'),
        ('back', '0066_auto_20201022_1624'),
    ]

    operations = [
    ]
