# Generated by Django 3.1 on 2020-10-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0067_merge_20201023_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foxuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
