# Generated by Django 3.1 on 2020-10-28 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0067_merge_20201023_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='hazardous_work',
        ),
    ]
