# Generated by Django 3.1 on 2020-10-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0068_remove_template_hazardous_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='hazardous_work',
            field=models.CharField(choices=[('None', 'None'), ('Work_At_Height', 'Work At Height'), ('Lifting_Work', 'Lifting Work'), ('Confined_Space', 'Confined Space'), ('Hot_Work', 'Hot Work'), ('Chemical_Handling', 'Chemical Handling'), ('Work_Alone', 'Work Alone'), ('Work_At_Sensitive_Area', 'Work At Sensitive Area'), ('Cold_Work', 'Cold Work')], default='None', max_length=25),
        ),
    ]
