# Generated by Django 3.1 on 2020-10-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0068_auto_20201026_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='contractors', to='back.Company'),
        ),
    ]
