# Generated by Django 3.1 on 2020-10-30 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0069_contractor_companies'),
        ('back', '0070_template_hazardous_work'),
    ]

    operations = [
    ]
