# Generated by Django 3.1 on 2020-11-13 06:21

import back.models.document
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0071_merge_20201030_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='filled_file',
            field=models.FileField(blank=True, null=True, upload_to=back.models.document.project_filled_files_path),
        ),
    ]
