# Generated by Django 3.1 on 2020-11-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0071_merge_20201030_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='applicant_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='applicant_phone',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
