# Generated by Django 3.1 on 2020-11-18 14:15

import back.models.contractor
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0073_project_submit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to=back.models.contractor.signature_img_path),
        ),
    ]
