# Generated by Django 3.1 on 2020-11-18 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0074_contractor_signature'),
        ('back', '0072_document_filled_file'),
    ]

    operations = [
    ]
