# Generated by Django 3.1 on 2020-11-25 21:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0077_auto_20201124_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.localtime, null=True),
        ),
    ]
