# Generated by Django 3.1 on 2020-12-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0079_auto_20201206_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Started', 'Started'), ('Completed', 'Completed'), ('Extended', 'Extended'), ('Closed', 'Closed')], default='Created', max_length=16),
        ),
    ]
