# Generated by Django 3.1 on 2021-02-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0080_auto_20201206_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='foxuser',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='new'),
        ),
    ]
